---
kind: Namespace
apiVersion: v1
metadata:
  name: homebridge
  labels:
    name: homebridge

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      hostNetwork: true
      containers:
      - name: homebridge
        image: homebridge/homebridge:latest
        ports:
        - name: config
          containerPort: 8581
        - name: bridge
          containerPort: 51342
        volumeMounts:
        - name: data
          mountPath: /homebridge
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homebridge-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pv
  namespace: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  selector:
    app: homebridge
  ports:
  - targetPort: 8581
    port: 8581
    protocol: TCP
    name: config-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge
  namespace: homebridge
spec:
  rules:
  - host: homebridge.mcintosh.farm
    http:
      paths:
      - backend:
          service:
            name: homebridge
            port:
              number: 8581
        path: /
        pathType: Prefix
