---
version: v1
kind: kubernetes
application: spinnaker-local
targets:
  local-cluster:
    account: local-cluster
    namespace: spinnaker
    strategy: simple

manifests:
  - path: cluster/spinnaker/minio-s3-for-kayenta.yaml
  - path: cluster/spinnaker/mysql.yaml
  - path: cluster/spinnaker/permissions.yaml
  - path: cluster/spinnaker/spinnaker.yaml

strategies:
  simple:
    canary:
      steps:
        - setWeight:
            weight: 100


