---
version: v1
kind: kubernetes
application: spinnaker-local
targets:
  local-cluster:
    account: local-cluster
    namespace: spinnaker
    strategy: simple

manifests:
  - path: local-spinnaker/armory-enterprise-operator/crds/
  - path: local-spinnaker/armory-enterprise-operator/operator/
  - path: local-spinnaker/


strategies:
  simple:
    canary:
      steps:
        - setWeight:
            weight: 100
