---
version: v1
kind: kubernetes
application: spinnaker-local
targets:
  local-cluster:
    account: local-cluster
    namespace: spinnaker
    strategy: simple

manifests:
  - path: local-spinnaker/armory-enterprise-operator/crds/
  - path: local-spinnaker/armory-enterprise-operator/operator/cluster/
  - path: local-spinnaker/example-namespaces.yaml
  - path: local-spinnaker/mysql.yaml
  - path: local-spinnaker/permissions.yaml
  - path: local-spinnaker/spinnaker.yaml


strategies:
  simple:
    canary:
      steps:
        - setWeight:
            weight: 100
