---
version: v1
kind: kubernetes
application: spinnaker-local
targets:
  local-cluster:
    account: local-cluster
    namespace: spinnaker
    strategy: simple

manifests:
  - path: cluster/spinnaker/*


strategies:
  simple:
    canary:
      steps:
        - setWeight:
            weight: 100
