ingressClass:
  isDefaultClass: false
  name: traefik

  ## It's a lab :) Expose the dashboard
ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true
providers:
  kubernetesIngress:
    ingressClass: "traefik"
  kubernetesCRD:
    ingressClass: "traefik"
