apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-spinnaker
  namespace: spinnaker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: spinnaker
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: spinnaker
data:
  config.cnf: |
    [mysqld]
    disable-log-bin=1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: spinnaker
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:9
        name: mysql
        env:
        - name: MYSQL_LOG_BIN
          value: "0"
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-storage
          mountPath: /etc/mysql/conf.d/
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pv-spinnaker
