ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
  hosts:
    - host: gitea.mcintosh.farm
  tls:
    - hosts:
      - "*.mcintosh.farm"
      secretName: mcintosh-farm
postgresql-ha:
  persistence:
    storageClass: rook-ceph-block
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi
