apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress-canary
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mcintosh.farm
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-web-app-service-canary
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress-baseline
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mcintosh.farm
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-web-app-service-baseline
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mcintosh.farm
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-web-app-service
            port: 
              number: 80

