apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-ingress-cert
  namespace: prod
spec:
  dnsNames:
  - '*.mcintosh.farm'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-issuer
  secretName: demo-ingress-cert
  usages:
  - digital signature
  - key encipherment

---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: demo-service
  namespace: prod
spec:
  weighted:
    services:
      - name: demo-web-app-service
        port: 8080
        weight: 8
      - name: demo-web-app-service-baseline
        port: 8080
        weight: 0
      - name: demo-web-app-service-canary
        port: 8080
        weight: 0
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: Host(`demo.mcintosh.farm`)
    kind: Rule
    observability:
      metrics: true
      accessLogs: true
    services:
    - name: demo-service
      kind: TraefikService 
  tls:
    secretName: demo-ingress-cert

