apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    app: demo-web-app
    type: spring-boot-app
  name: demo-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-web-app
  template:
    metadata:
      annotations:
        type: spring-boot-app
    spec:
      containers:
        - name: demo-web-app
          ## INTENTIONALLY not tagging resources so spinnaker can pick it up
          image: ghcr.io/jasonmcintosh/spinnaker-work/demo-web-app
---
apiVersion: v1
kind: Service
metadata:
  name: demo-web-app-service
  annotations:
    app: demo-web-app
    type: spring-boot-app
spec:
  selector:
    app: demo-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
