apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: harness
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      prometheusremotewrite:
        endpoint: https://prometheus.mcintosh.farm/api/v1/write
      
    processors:
      batch:
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheusremotewrite]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
  namespace: harness
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetrycollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetrycollector
    spec:
      containers:
      - name: otelcol
        ports:
          - containerPort: 4318
            protocol: TCP
          - containerPort: 4317
            protocol: TCP
        args:
        - --config=/conf/collector.yaml
        image: otel/opentelemetry-collector:latest
        volumeMounts:
        - mountPath: /conf
          name: collector-config
      volumes:
      - configMap:
          items:
          - key: collector.yaml
            path: collector.yaml
          name: collector-config
        name: collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
  namespace: harness
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-protobuff
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP
