apiVersion: v1
kind: Service
metadata:
  name: nginx-ingresses
  namespace: ingress-nginx
spec:
  selector:
    name: traefk-ingress-service
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
