apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: debugging-tools
  name: debugging-tools
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: debugging-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: debugging-tools
    spec:
      containers:
        - command:
            - tail
            - '-f'
            - /dev/null
          image: 'armory/debugging-tools:latest'
          imagePullPolicy: Always
          name: debugging-tools
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

