pipeline:
  name: Update DNS
  identifier: Update_DNS
  projectIdentifier: DNS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: TF Apply
        identifier: TF_Apply
        description: Updates cloudflare DNS Data
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: ApplyDNS
                  identifier: ApplyDNS
                  spec:
                    provisionerIdentifier: tf_dns_internal
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            spec:
                              repoName: spinnaker-work
                              gitFetchType: Branch
                              branch: main
                              folderPath: applications/tf-dns-internal
                              connectorRef: GitHubPersonal
                            type: Github
                  timeout: 15m
        tags: {}
