name: Demo-Web-App - Build

on:
  push: # What triggers a deployment. For example, `push`.
    paths:
      - 'applications/demo-web-app/**'
      - '.github/workflows/build-demo-app.yaml'
    ## Don't fire a build if a manifest changes :) 
    paths-ignore:
      - 'applications/demo-web-app/manifests/**'
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jasonmcintosh/spinnaker-work/demo-web-app

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
        working-directory: applications/demo-web-app/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK    
        uses: actions/setup-java@v3
        with:        
         java-version: 17
         distribution: corretto
         cache: gradle

      - name: Gradle build and push
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: applications/demo-web-app/
          arguments: |
            -PimagePush=true 
            -PimageCacheFrom=type=gha
            -PimageCacheTo=type=gha,mode=max
            buildSimpleBootImage
